name: "Run tests"
on:
  pull_request:
  push:

jobs:
  tests:
    strategy:
      matrix:
        nixRelease:
          - nixpkgs-unstable
          - nixos-unstable
          - nixos-24.11
          - nixos-25.05
    runs-on: ubuntu-latest
    env:
      nixPath: "nixpkgs=https://github.com/NixOS/nixpkgs/archive/refs/heads/${{ matrix.nixRelease }}.tar.gz"
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install nix
      uses: cachix/install-nix-action@v30
      with:
        nix_path: "${{ env.nixPath }}"
        extra_nix_config: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - name: Show nixpkgs version
      run: nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version'
    - name: Run flake checks
      run: nix flake check
    - name: Build packages using flake
      run: nix build
    - name: Run standard metapackage test
      run: nix run '.#test.meta-standard'
